name = "envision-leads"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
ALLOW_ORIGINS = ""
RECAPTCHA_SECRET = ""
FROM_EMAIL = "EnVision <noreply@yourdomain>"
TO_EMAIL = "hello@envision.studio"
GSHEET_WEBAPP_URL = ""
GSHEET_SECRET = ""

# Secrets to add with wrangler:
# wrangler secret put RESEND_API_KEY
